export const links: { [key: string]: string } = {
	"angular": 'https://angular.io/',
	"react": 'https://reactjs.org/',
	"vue.js": 'https://vuejs.org/',
	"node.js": 'https://nodejs.org/',
	"express": 'https://expressjs.com/',
	"mongodb": 'https://www.mongodb.com/',
	"mysql": 'https://www.mysql.com/',
	"postgresql": 'https://www.postgresql.org/',
	"python": 'https://www.python.org/',
	"django": 'https://www.djangoproject.com/',
	"flask": 'https://flask.palletsprojects.com/',
	"java": 'https://www.java.com/',
	"spring": 'https://spring.io/',
	"spring boot": 'https://spring.io/projects/spring-boot',
	"html": 'https://developer.mozilla.org/en-US/docs/Web/HTML',
	"css": 'https://developer.mozilla.org/en-US/docs/Web/CSS',
	"javascript": 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
	"typescript": 'https://www.typescriptlang.org/',
	"jquery": 'https://jquery.com/',
	"bootstrap": 'https://getbootstrap.com/',
	"materialize": 'https://materializecss.com/',
	"tailwind css": 'https://tailwindcss.com/',
	"firebase": 'https://firebase.google.com/',
	"aws": 'https://aws.amazon.com/',
	"docker": 'https://www.docker.com/',
	"git": 'https://git-scm.com/',
	"linux": 'https://www.linux.org/',
	"windows": 'https://www.microsoft.com/en-us/windows',
	"macos": 'https://www.apple.com/macos/',
	"c": 'https://en.wikipedia.org/wiki/C_(programming_language)',
	"c++": 'https://en.wikipedia.org/wiki/C%2B%2B',
	"c#": 'https://en.wikipedia.org/wiki/C_Sharp_(programming_language)',
	"php": 'https://www.php.net/',
	"rust": 'https://www.rust-lang.org/',
	"swift": 'https://developer.apple.com/swift/',
	"objective-c": 'https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html',
	"dart": 'https://dart.dev/',
	"flutter": 'https://flutter.dev/',
	"unity": 'https://unity.com/',
	"unreal engine": 'https://www.unrealengine.com/',
	"ocaml": 'https://ocaml.org/',
	"sdl2": 'https://www.libsdl.org/',
	"opengl": 'https://www.opengl.org/',
	"vulkan": 'https://www.khronos.org/vulkan/',
	"directx": 'https://www.microsoft.com/en-us/directx',
	"opencl": 'https://www.khronos.org/opencl/',
	"javafx": 'https://openjfx.io/',
	"sfml": 'https://www.sfml-dev.org/',
	"unix": 'https://en.wikipedia.org/wiki/Unix',
	"bash": 'https://www.gnu.org/software/bash/',
	"powershell": 'https://docs.microsoft.com/en-us/powershell/',
	"zsh": 'https://www.zsh.org/',
	"vim": 'https://www.vim.org/',
	"emacs": 'https://www.gnu.org/software/emacs/',
	"neovim": 'https://neovim.io/',
	"vscode": 'https://code.visualstudio.com/',
	"atom": 'https://atom.io/',
	"sublime text": 'https://www.sublimetext.com/',
	"intellij idea": 'https://www.jetbrains.com/idea/',
	"eclipse": 'https://www.eclipse.org/',
	"pycharm": 'https://www.jetbrains.com/pycharm/',
	"clion": 'https://www.jetbrains.com/clion/',
	"android studio": 'https://developer.android.com/studio',
	"xcode": 'https://developer.apple.com/xcode/',
	"visual studio": 'https://visualstudio.microsoft.com/',
	"qt": 'https://www.qt.io/',
	"blender": 'https://www.blender.org/',
	"maya": 'https://www.autodesk.com/products/maya/overview',
	"3ds max": 'https://www.autodesk.com/products/3ds-max/overview',
	"photoshop": 'https://www.adobe.com/products/photoshop.html',
	"illustrator": 'https://www.adobe.com/products/illustrator.html',
	"after effects": 'https://www.adobe.com/products/aftereffects.html',
	"premiere": 'https://www.adobe.com/products/premiere.html',
	"audition": 'https://www.adobe.com/products/audition.html',
	"audacity": 'https://www.audacityteam.org/',
	"fl studio": 'https://www.image-line.com/flstudio/',
	"ableton": 'https://www.ableton.com/en/',
	"logic pro": 'https://www.apple.com/logic-pro/',
	"garageband": 'https://www.apple.com/garageband/',
	"coq": 'https://coq.inria.fr/',
	"cmake": 'https://cmake.org/',
	"make": 'https://www.gnu.org/software/make/',
	"github": 'https://github.com',
	"gitlab": 'https://gitlab.com/',
	"sql": 'https://en.wikipedia.org/wiki/SQL',
	"vite": 'https://vitejs.dev/',
	"gradle": 'https://gradle.org/',
	"maven": 'https://maven.apache.org/',
	"webassembly": 'https://webassembly.org/',
	"paint.net": 'https://www.getpaint.net/',
	"next.js": 'https://nextjs.org/',
	"nuxt.js": 'https://nuxtjs.org/',
	"graphql": 'https://graphql.org/',
	"redux": 'https://redux.js.org/',
	"sass": 'https://sass-lang.com/',
	"less": 'http://lesscss.org/',
	"npm": 'https://www.npmjs.com/',
	"yarn": 'https://yarnpkg.com/',
	"webpack": 'https://webpack.js.org/',
	"parcel": 'https://parceljs.org/',
	"semantic ui": 'https://semantic-ui.com/',
	"ant design": 'https://ant.design/',
	"ionic": 'https://ionicframework.com/',
	"electron": 'https://www.electronjs.org/',
	"docker-compose": 'https://docs.docker.com/compose/',
	"jest": 'https://jestjs.io/',
	"mocha": 'https://mochajs.org/',
	"chai": 'https://www.chaijs.com/',
	"cypress": 'https://www.cypress.io/',
	"tailwind ui": 'https://tailwindui.com/',
	"storybook": 'https://storybook.js.org/',
	"testing-library": 'https://testing-library.com/',
	"postman": 'https://www.postman.com/',
	"insomnia": 'https://insomnia.rest/',
	"r": 'https://www.r-project.org/',
	"shiny": 'https://shiny.rstudio.com/',
	"scala": 'https://www.scala-lang.org/',
	"kotlin": 'https://kotlinlang.org/',
	"elixir": 'https://elixir-lang.org/',
	"go": 'https://golang.org/',
	"haskell": 'https://www.haskell.org/',
	"julia": 'https://julialang.org/',
	"html5": 'https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5',
	"css3": 'https://www.w3.org/TR/css3-roadmap/',
	"web components": 'https://webcomponents.org/',
	"service workers": 'https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API',
	"prisma": 'https://www.prisma.io/',
	"gcp": 'https://cloud.google.com/',
	"azure": 'https://azure.microsoft.com/',
	"heroku": 'https://www.heroku.com/',
	"digital ocean": 'https://www.digitalocean.com/',
};
export function getTechLink(tech: string): string {
	for (const key in links) {
		if (tech.toLowerCase() === key) {
			return links[key]
		}
	}
	return ''
}